// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw6mOBBW9XWyvbDgMnDt3BRWNhX2anlgM',
    appId: '1:870831073211:web:08b6f088471fd14155069e',
    messagingSenderId: '870831073211',
    projectId: 'my-commute-app-000',
    authDomain: 'my-commute-app-000.firebaseapp.com',
    storageBucket: 'my-commute-app-000.firebasestorage.app',
    measurementId: 'G-SJ7PQFDH5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMioVnX6PIfalAqoQbCz1IAsEz19dv9iE',
    appId: '1:870831073211:android:2ee30547d5005b8e55069e',
    messagingSenderId: '870831073211',
    projectId: 'my-commute-app-000',
    storageBucket: 'my-commute-app-000.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdYtGEdxREgMZrz1uaHGcfQQXbw4qbwZg',
    appId: '1:870831073211:ios:1bfc4a36144a887055069e',
    messagingSenderId: '870831073211',
    projectId: 'my-commute-app-000',
    storageBucket: 'my-commute-app-000.firebasestorage.app',
    androidClientId: '870831073211-sd5v21eahbq2l5orvmd60hk3j1iu0hee.apps.googleusercontent.com',
    iosClientId: '870831073211-j1of26b1enimaqudm5cn34tul8uvnbjs.apps.googleusercontent.com',
    iosBundleId: 'com.commuteshare.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdYtGEdxREgMZrz1uaHGcfQQXbw4qbwZg',
    appId: '1:870831073211:ios:1bfc4a36144a887055069e',
    messagingSenderId: '870831073211',
    projectId: 'my-commute-app-000',
    storageBucket: 'my-commute-app-000.firebasestorage.app',
    androidClientId: '870831073211-sd5v21eahbq2l5orvmd60hk3j1iu0hee.apps.googleusercontent.com',
    iosClientId: '870831073211-j1of26b1enimaqudm5cn34tul8uvnbjs.apps.googleusercontent.com',
    iosBundleId: 'com.commuteshare.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL2H680UutlhwP1mO2bIKWlK7tPMXFPOs',
    appId: '1:870831073211:web:a0c826d5fa98c00d55069e',
    messagingSenderId: '870831073211',
    projectId: 'my-commute-app-000',
    authDomain: 'my-commute-app-000.firebaseapp.com',
    storageBucket: 'my-commute-app-000.firebasestorage.app',
    measurementId: 'G-0762SBWPKQ',
  );

}